version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pm
      POSTGRES_USER: pmuser
      POSTGRES_PASSWORD: pmpass
    volumes: [dbdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pmuser -d pm"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./backend
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: pm
      POSTGRES_USER: pmuser
      POSTGRES_PASSWORD: pmpass
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]

  web:
    build: ./frontend
    depends_on: [api]
    ports: ["5173:80"]

volumes:
  dbdata: {}
