# Generated by Django 4.2.14 on 2025-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='core_projec_organiz_89f076_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['due_date'], name='core_projec_due_dat_63bac9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='core_task_project_3c46c4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee_email'], name='core_task_assigne_040aab_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='core_task_due_dat_d0a0d3_idx'),
        ),
    ]
