name: backend

on:
  push:
    paths: ["backend/**", ".github/workflows/backend.yml"]
  pull_request:
    paths: ["backend/**", ".github/workflows/backend.yml"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: pm
          POSTGRES_USER: pmuser
          POSTGRES_PASSWORD: pmpass
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U pmuser -d pm"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django

      - name: Env
        working-directory: backend
        run: |
          echo "POSTGRES_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
          echo "POSTGRES_DB=pm" >> $GITHUB_ENV
          echo "POSTGRES_USER=pmuser" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=pmpass" >> $GITHUB_ENV
          echo "DEBUG=False" >> $GITHUB_ENV
          echo "ALLOWED_HOSTS=*" >> $GITHUB_ENV

      - name: Migrate
        working-directory: backend
        run: python manage.py migrate

      - name: Tests
        working-directory: backend
        run: pytest -q
