name: frontend

on:
  push:
    paths: ["frontend/**", ".github/workflows/frontend.yml"]
  pull_request:
    paths: ["frontend/**", ".github/workflows/frontend.yml"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        working-directory: frontend
        run: npm ci

      - name: Typecheck
        working-directory: frontend
        run: npx tsc --noEmit

      - name: Build
        working-directory: frontend
        env:
          VITE_API_URL: http://localhost:8000/graphql
        run: npm run build
